"""init

Revision ID: 84f45dd0aff8
Revises: 
Create Date: 2026-01-26 11:07:35.642169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f45dd0aff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('default_threshold_percent', sa.Float(), server_default=sa.text('(5.0)'), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('prices_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices_history', schema=None) as batch_op:
        batch_op.create_index('idx_prices_history_product_id_fetched_at', ['product_id', 'fetched_at'], unique=False)

    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('raw_api_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_api_responses', schema=None) as batch_op:
        batch_op.create_index('idx_raw_api_responses_fetched_at', ['fetched_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('threshold_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'product_id', name='pk_subscriptions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    with op.batch_alter_table('raw_api_responses', schema=None) as batch_op:
        batch_op.drop_index('idx_raw_api_responses_fetched_at')

    op.drop_table('raw_api_responses')
    op.drop_table('products')
    with op.batch_alter_table('prices_history', schema=None) as batch_op:
        batch_op.drop_index('idx_prices_history_product_id_fetched_at')

    op.drop_table('prices_history')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
